#!/bin/sh

alias sudo='sudo '

alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'
alias vi='nvim'

alias g++='g++ -std=c++17'

alias tre='tmux attach'
alias tat='tmux attach-session -t'
alias tdt='tmux detach'
alias tkt='tmux kill-session -t'
alias tst='tmux switch -t'
alias tns='tmux new -s'
alias tls='tmux ls'

alias ofd='open .'

alias pgh='GITHUB_TOKEN=$PERSONAL_GITHUB_TOKEN gh'
alias wgh='GITHUB_TOKEN=$WORK_GITHUB_TOKEN gh'

alias live-server='live-server --port=8080 --browser=chromium'

alias bat='bat --style=plain'
alias 'bat -nu'='bat --style=numbers'

alias kts='kotlinc -script'

alias d='dirs -v'
alias 0='cd -0 &> /dev/null'
alias 1='cd -1 &> /dev/null'
alias 2='cd -2 &> /dev/null'
alias 3='cd -3 &> /dev/null'
alias 4='cd -4 &> /dev/null'
alias 5='cd -5 &> /dev/null'
alias 6='cd -6 &> /dev/null'
alias 7='cd -7 &> /dev/null'
alias 8='cd -8 &> /dev/null'
alias 9='cd -9 &> /dev/null'

alias lazygit='lazygit --use-config-file=$HOME/.config/lazygit/config.yml'
alias lg='lazygit --use-config-file=$HOME/.config/lazygit/config.yml'

alias cz='chezmoi'
alias cvi='chezmoi edit --watch --hardlink=false'
alias czg='chezmoi git'
alias czu='chezmoi update'
alias czap='chezmoi apply'
alias czad='chezmoi add'
alias czc='chezmoi cd'
alias czr='chezmoi remove'
alias czf='chezmoi forget'

alias tf='terraform'
alias tfi='terraform init'
alias tfg='terraform get'
alias tfr='terraform refresh'
alias tfo='terraform output'
alias tfd='terraform destroy'
alias tfu='terraform get --update'
alias tfa='terraform get --update && terraform apply'
alias tfp='terraform plan'

alias dcp='docker-compose'
alias py='python3'
