#!/bin/sh

#alias tmux='tmux new-session -A -s main'

alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'

# if [[ $CUR_OS == 'linux' ]]; then
#   alias ls='ls --color'
# fi

alias g++='g++ -std=c++17'

alias tre='tmux attach'
alias tat='tmux attach-session -t'
alias tdt='tmux detach'
alias tkt='tmux kill-session -t'
alias tst='tmux switch -t'
alias tns='tmux new -s'
alias tls='tmux ls'

alias ofd='open .'

alias pgh='GITHUB_TOKEN=$PERSONAL_GITHUB_TOKEN gh'
alias wgh='GITHUB_TOKEN=$WORK_GITHUB_TOKEN gh'

alias live-server='live-server --port=8080 --browser=chromium'

alias bat='bat --style=plain'
alias 'bat -nu'='bat --style=numbers'

alias kts='kotlinc -script'

alias d='dirs -v'
alias 0='cd -0'
alias 1='cd -1'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'

alias lazygit='lazygit --use-config-file=$HOME/.config/lazygit/config.yml'
alias lg='lazygit --use-config-file=$HOME/.config/lazygit/config.yml'

alias cz='chezmoi'
alias czg='chezmoi git'
alias czp='chezmoi update'
alias czap='chezmoi apply'
alias czcd='chezmoi cd'
alias czrm='chezmoi remove'
alias czfg='chezmoi forget'

alias tf='terraform'
alias tfi='terraform init'
alias tfg='terraform get'
alias tfa='terraform apply'
alias tfl='terraform plan'
alias tfd='terraform destroy'
alias tfgu='terraform get --update'

alias tf='terraform'
alias tf='terraform'
alias dcp='docker-compose'
