#!/bin/sh

#alias tmux='tmux new-session -A -s main'

alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'

# if [[ $CUR_OS == 'linux' ]]; then
#   alias ls='ls --color'
# fi

alias g++='g++ -std=c++17'

alias vi='nvim'

alias tre='tmux attach'
alias tat='tmux attach-session -t'
alias tdt='tmux detach'
alias tkt='tmux kill-session -t'
alias tst='tmux switch -t'
alias tns='tmux new -s'
alias tls='tmux ls'

alias ofd='open .'

# alias personal-hub='GITHUB_TOKEN=$GIT_PERSONAL_TOKEN hub pull-request -b main -h $(git rev-parse --abbrev-ref HEAD)'
alias mkpr='hub_make_pr'
alias lspr='hub_list_pr'
alias mgpr='hub_merge_pr'

alias live-server='live-server --port=8080 --browser=chromium'

alias bat='bat --style=plain'
alias 'bat -nu'='bat --style=numbers'

alias kts='kotlinc -script'

alias d='dirs -v'
alias 0='cd -0'
alias 1='cd -1'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'

alias lazygit='lazygit --use-config-file=$HOME/.config/lazygit/config.yml'
alias lg='lazygit --use-config-file=$HOME/.config/lazygit/config.yml'
