#!/bin/sh

skip_global_compinit=1

zmodload zsh/nearcolor

autoload -U promptinit; promptinit
# autoload -Uz compinit && compinit -i

if [[ $CUR_OS == 'linux' ]]; then
    autoload -Uz compinit
    for dump in ~/.zcompdump(N.mh+24); do
        compinit -i
    done
    compinit -C
elif [[ $CUR_OS == 'mac' ]]; then
    autoload -Uz compinit
    if [ $(date +'%j') != $(stat -f '%Sm' -t '%j' ~/.zcompdump) ]; then
        compinit -i
    else
        compinit -C
    fi
fi
