#!/bin/zsh

#alias tmux='tmux new-session -A -s main'

alias ll='ls -alFh'
alias la='ls -A'
alias l='ls -CF'

alias g++='g++ -std=c++17'

alias vi='nvim'

alias tre='tmux attach'
alias tat='tmux attach-session -t'
alias tkt='tmux kill-session -t'
alias tst='tmux switch -t'
alias tns='tmux new -s'
alias tls='tmux ls'

alias live-server='live-server --port=8080 --browser=chromium'

alias bat='bat --style=plain'
alias 'bat -nu'='bat --style=numbers'

# automatically run tmux on startup
#if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
  #exec tmux new-session -A -s main
#fi

# enable color support of ls and also add handy aliases
#if [ -x /usr/bin/dircolors ]; then
	##test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    #alias ls='ls --color=auto'
	##alias dir='dir --color=auto'
	##alias vdir='vdir --color=auto'

	#alias grep='grep --color=auto'
	#alias fgrep='fgrep --color=auto'
	#alias egrep='egrep --color=auto'
#fi
