#!/bin/zsh

# PATHS
export ZSH="$HOME/.oh-my-zsh"
export LOCAL_BIN=$HOME/.local/bin

export PATH="/usr/local/sbin:$PATH"
export PATH=${PATH}:$LOCAL_BIN
export PATH="/usr/local/opt/llvm/bin:$PATH"

# ENV
export KRY_DB_USERNAME="root"
export KRY_DB_PASS="1234"
export KRY_DB_PORT="3307"
export KRY_DB_IP="localhost"
export KRY_DB="test"
export WORKON_HOME=~/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON='/usr/local/bin/python3'  # Usage of python3

# esc key delay 
export KEYTIMEOUT=1 

export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'


