#!/bin/zsh

sudo yabai --load-sa

sketchybar --config ~/.config/yabai/sketchybar/sketchybarrc &

yabai -m config layout bsp

yabai -m config split_ratio 0.5

yabai -m config window_opacity on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.9

yabai -m config top_padding    8
yabai -m config bottom_padding 8
yabai -m config left_padding   8
yabai -m config right_padding  8
yabai -m config window_gap     8

yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add title="^Settings$" manage=off
yabai -m rule --add app="KakaoTalk" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add app="Spotify" manage=off
yabai -m rule --add app="1Password" manage=off
yabai -m rule --add app="Alfred*" manage=off

