#!/bin/zsh
if [[ $1 == "--u" ]]; then
    sudo iptables -A INPUT -p tcp --tcp-flags RST RST --sport 443 -j DROP
    echo "IPTABLES RULE ADDED"
elif [[ $1 == "--d" ]]; then
    sudo iptables -D INPUT -p tcp --tcp-flags RST RST --sport 443 -j DROP
    echo "IPTABLES RULL DELETED"
fi
    
