#!/bin/zsh
# vim:filetype=zsh:tw=80:et

export DOT_ZSH=$HOME/.zsh

plugins=(
    # git
    fzf
    vi-mode
    zsh-defer
    zsh-syntax-highlighting
    autoswitch_virtualenv
)

fpath+="$DOT_ZSH/pure"
fpath+="$DOT_ZSH/_completion"

source "$DOT_ZSH/oh-my-zsh/oh-my-zsh.sh"
source "$DOT_ZSH/style.zsh"
source "$DOT_ZSH/alias.zsh"
source "$DOT_ZSH/opt.zsh"
source "$DOT_ZSH/keymap.zsh"

for file in $HOME/.zsh/util/*
do
  source "$file"
done

[ -f ~/.profile ] && zsh-defer source "$HOME/.profile"
[ -f ~/.secrets ] && zsh-defer source "$HOME/.secrets"

# autoload -U +X compinit && compinit
autoload -U promptinit; promptinit
prompt pure

zmodload zsh/zprof

# _run_tmux_if_terminal_is_one_of "WezTerm" "alacritty"
