#!/bin/zsh

# ┌─────────┐ 
# │ OPENVPN │ 
# └─────────┘ 
export OVPN_ROOT="$HOME/vpn"
export OVPN_DATA="$HOME/vpn/data"
alias vpn='sudo openvpn --setenv PATH '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' --up /etc/openvpn/update-resolv-conf --down /etc/openvpn/update-resolv-conf --script-security 2 --down-pre'

# ┌───────────────────┐ 
# │ JETBRAINS TOOLBOX │ 
# └───────────────────┘ 
export PATH="$PATH:/home/jerry/.local/share/JetBrains/Toolbox/scripts"

# ┌───────────┐ 
# │ SPOOF-DPI │ 
# └───────────┘ 
export PATH="$PATH:~/.spoof-dpi/bin"

# ┌───────┐ 
# │ CARGO │ 
# └───────┘ 
. "$HOME/.cargo/env"

# ┌───────────┐ 
# │ 1PASSWORD │ 
# └───────────┘ 
_is_linux && export SSH_AUTH_SOCK=~/.1password/agent.sock
_is_darwin && \
  export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock

# ┌────────┐ 
# │ DOCKER │ 
# └────────┘ 
export PATH="$PATH:/Applications/Docker.app/Contents/Resources/bin/"

# ┌────┐ 
# │ GO │ 
# └────┘ 
command -v go &> /dev/null && export PATH=`go env GOPATH`/bin:$PATH

# ┌──────────┐ 
# │ BOB NVIM │ 
# └──────────┘ 
command -v bob &> /dev/null && export PATH="$HOME/.local/share/bob/nvim-bin:$PATH"

# ┌───────┐ 
# │ PYENV │ 
# └───────┘ 
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
command -v pyenv > /dev/null && eval "$(pyenv init --path)"

# ┌────────┐ 
# │ SDKMAN │ 
# └────────┘ 
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
