#!/bin/zsh
# vim:filetype=sh:tw=80:et

export ZSH=~/.oh-my-zsh

plugins=(
    git
    fzf
    docker
    vi-mode
)
zstyle ':omz:plugins:docker' legacy-completion yes


ZSH_DISABLE_COMPFIX="true"

fpath+=$HOME/.zsh/pure
fpath+=$HOME/.zsh/_completion_sources

autoload -U promptinit; promptinit

source $ZSH/oh-my-zsh.sh
source ~/.zsh/env
source ~/.zsh/completion
source ~/.zsh/aliases
source ~/.zsh/opt
source ~/.zsh/prompt
source ~/.zsh/keymaps
source ~/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

for file in ~/.zsh/util/*; do
    source "$file"
done

source $HOME/.profile

zmodload zsh/zprof

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

prompt pure

git config --global user.useConfigOnly true
