#!/bin/zsh

# ┌─────────────┐ 
# │ ZSH_OPTIONS │ 
# └─────────────┘ 
setopt no_global_rcs

# ┌───────────┐ 
# │ DETECT_OS │ 
# └───────────┘ 
export CUR_OS=$(uname)

if [ "$CUR_OS" = "Darwin" ]; then
  function _is_darwin() { return 0 }
else
  function _is_darwin() { return 1 }
fi

if [ "$CUR_OS" = "Linux" ]; then
  function _is_linux() { return 0 }
else
  function _is_linux() { return 1 }
fi

# ┌────────────┐ 
# │ COMMON ENV │ 
# └────────────┘ 
export CLICOLOR=1
export CLICOLOR_FORCE=1

# reduce esc delay 
export KEYTIMEOUT=1 

# set default editor to nvim
export EDITOR=nvim

# PATHS
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.scripts/git:$PATH"

