#!/bin/sh

echo ""
echo "[HOOKS]"

echo "  Running ln -f ~/dotfiles/shell/zshrc ~/.zshrc"
ln -f ~/dotfiles/shell/zshrc ~/.zshrc

echo "  Running ln -f ~/dotfiles/nvim/init.vim ~/.config/nvim/init.vim"
ln -f ~/dotfiles/nvim/init.vim ~/.config/nvim/init.vim

echo "  Running ln -f ~/dotfiles/tmux/tmux.conf.local ~/.tmux.conf.local"
ln -f ~/dotfiles/tmux/tmux.conf.local ~/.tmux.conf.local

echo "[DONE]"
