#!/usr/bin/env bash

HELP="usage: git set --org [organization name]"

while [[ $# -gt 0 ]]; do
	case $1 in
	-o | --org)
		org="$2"
		shift
		shift
		;;
	-h | --help)
		shift
		echo $HELP
		exit 1
		;;
	*)
		shift # past argument
		;;
	esac
done

if [ -z "$org" ]; then
	echo $HELP
	exit 1
fi

# https://github.com/xvzc/dotfiles.git
origin=$(git remote get-url origin)
tokens=($(echo $origin | tr "/" "\n"))
repo=${tokens[${#tokens[@]} - 1]}

git remote set-url --push origin "git@$org.github.com:$org/$repo"
