#!/bin/sh

if [ "$1" = "--personal" ] || [ "$1" = "-p" ]; then
  GITHUB_TOKEN=$PERSONAL_GITHUB_TOKEN\
    hub pull-request -b $2 -h $(git rev-parse --abbrev-ref HEAD)
elif [ "$1" = "--work" ] || [ "$1" = "-w" ]; then
  GITHUB_TOKEN=$WORK_GITHUB_TOKEN\
    hub pull-request -b $2 -h $(git rev-parse --abbrev-ref HEAD)
else
  echo "Invalid option."
  echo "Usage: $(basename $0)-[p | w] [destination-branch]"
  exit 1
fi
