#!/bin/sh

REMOTE_URL=$(git remote get-url origin)
echo "Remote URL: $REMOTE_URL" 

END_IDX=0
for ((i=${#REMOTE_URL}-1; i>=0; i--)); do
  if [ "${REMOTE_URL:$i:1}" = "." ]; then
    END_IDX=$i
    break
  fi
done

START_IDX=0
for ((i=$END_IDX-1; i>=0; i--)); do
  if [ "${REMOTE_URL:$i:1}" = "/" ]; then
    START_IDX=$i
    break
  fi
done

for ((i=$START_IDX-1; i>=0; i--)); do
  if [ "${REMOTE_URL:$i:1}" = "/" ]; then
    START_IDX=$i
    break
  fi
done

MERGE_ENDPOINT="repos/${REMOTE_URL:$START_IDX + 1:$END_IDX - $START_IDX - 1}/pulls/$2/merge"
echo "Merging pull request: $MERGE_ENDPOINT\n"

if [ "$1" = "--personal" ] || [ "$1" = "-p" ]; then
  GITHUB_TOKEN=$PERSONAL_GITHUB_TOKEN hub api -XPUT $MERGE_ENDPOINT $3
elif [ "$1" = "--work" ] || [ "$1" = "-w" ]; then
  GITHUB_TOKEN=$WORK_GITHUB_TOKEN hub api -XPUT $MERGE_ENDPOINT $3
else
  echo "Invalid option."
  echo "Usage: $0 [option] [pull-request-id]"
  exit 1
fi
