#!/bin/sh

if [ "$1" = "--personal" ] || [ "$1" = "-p" ]; then
  GITHUB_TOKEN=$PERSONAL_GITHUB_TOKEN hub pr list
elif [ "$1" = "--work" ] || [ "$1" = "-w" ]; then
  GITHUB_TOKEN=$WORK_GITHUB_TOKEN hub pr list
else
  echo "Invalid option."
  echo "Usage: $0 [option]"
  exit 1
fi
