#!/bin/sh

HELP="usage: git ssh --user [username] [clone options]"

ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    -u|--user)
      git_user="$2"
      shift
      shift
      ;;
    -h|--help)
      shift
      echo $HELP
      exit 1
      ;;
    *)
      ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

if [ -z "$git_user" ]; then
  echo $HELP
  exit 1;
fi

set -- "${ARGS[@]}" # restore positional parameters
for i in "${!ARGS[@]}"; do
  if [[ ${ARGS[$i]} == *"github.com"* ]]; then
    ARGS[$i]=$(echo "${ARGS[$i]}" | sed "s/github.com/$git_user.github.com/g")
  fi
done

for ARG in ${ARGS[@]}; do
  echo "This is ${ARG}"
done

git clone "${ARGS[@]}"
