#!/bin/sh  

if [ "$1" = "--personal" ] || [ "$1" = "-p" ]; then
  GITHUB_UNAME=$PERSONAL_GITHUB_UNAME
  GITHUB_EMAIL=$PERSONAL_GITHUB_EMAIL
  GITHUB_TOKEN=$PERSONAL_GITHUB_TOKEN
elif [ "$1" = "--work" ] || [ "$1" = "-w" ]; then
  GITHUB_UNAME=$WORK_GITHUB_UNAME
  GITHUB_EMAIL=$WORK_GITHUB_EMAIL
  GITHUB_TOKEN=$WORK_GITHUB_TOKEN
else
  echo "Invalid option."
  echo "Usage: $(basename $0) -[p | w]"
  exit 1
fi

git config --local user.email $GITHUB_EMAIL
git config --local user.name $GITHUB_UNAME

REPO_URL=$(git config --local remote.origin.url | grep -o -e "github.com.*")
git config --local remote.origin.url \
  $(echo "https://$GITHUB_UNAME:$GITHUB_TOKEN@$REPO_URL")

git config --local push.autoSetupRemote true
git config --local commit.template ~/.asset/gitmessage.txt
