#!/usr/bin/env bash

HELP="usage: git set --user [username]"

while [[ $# -gt 0 ]]; do
  case $1 in
    -u|--user)
      git_user="$2"
      shift
      shift
      ;;
    -h|--help)
      shift
      echo $HELP
      exit 1
      ;;
    *)
      shift # past argument
      ;;
  esac
done

if [ -z "$git_user" ]; then
  echo $HELP
  exit 1;
fi

# https://github.com/xvzc/dotfiles.git
origin=$(git remote get-url origin)
tokens=($(echo $origin | tr "/" "\n"))
repo=${tokens[${#tokens[@]}-1]}
echo $git_user
echo $repo

git remote set-url --push origin "git@$git_user.github.com:$git_user/$repo"

