#!/bin/zsh

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(fd --search-path ~/.config --search-path ~/.scripts --search-path ~/_personal --search-path ~/_work --search-path ~/playground --type f --hidden | fzf-tmux -p80%,60% --preview 'bat')
fi

if [[ -z $selected ]]; then
    exit 0
fi

tmux new-window "nvim $selected"
