#!/bin/bash
if [[ $1 == "-u" ]]; then
    if [[ $(sudo iptables -C INPUT -p tcp --tcp-flags RST RST --sport 443 -j DROP 2> /dev/null) ]]; then
        echo "RST Drop Rule already exists"
    else
        sudo iptables -A INPUT -p tcp --tcp-flags RST RST --sport 443 -j DROP
        echo "RST Drop Rule added"
    fi
elif [[ $1 == "-d" ]]; then
    if [[ $(sudo iptables -C INPUT -p tcp --tcp-flags RST RST --sport 443 -j DROP 2> /dev/null) ]]; then
        sudo iptables -D INPUT -p tcp --tcp-flags RST RST --sport 443 -j DROP
        echo "RST Drop Rule deleted"
    else
        echo "RST Drop Rule not found"
    fi
fi
