#!/bin/sh

HELP="usage: git get --profile [profile] [options]"

ARGS=()

while [[ $# -gt 0 ]]; do
  case $1 in
    -p|--profile)
      PROFILE="$2"
      shift
      shift
      ;;
    -h|--help)
      shift
      echo $HELP
      exit 1
      ;;
    *)
      ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

if [ -z "$PROFILE" ]; then
  echo $HELP
  exit 1;
fi

set -- "${ARGS[@]}" # restore positional parameters
for i in "${!ARGS[@]}"; do
  if [[ ${ARGS[$i]} == *"github.com"* ]]; then
    ARGS[$i]=$(echo "${ARGS[$i]}" | sed "s/github.com/$PROFILE.github.com/g")
  fi
done

for ARG in ${ARGS[@]}; do
  echo "This is ${ARG}"
done

git clone "${ARGS[@]}"
